apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: tanzu-gunter
spec:
  portal:
    title: Tanzu Academy / Guides
    sessions:
      maximum: 30
      registered: 1 # this prevents a person from running more than one active lab/guide from this at a time
    updates:
      workshop: true
    theme:
      frame:
        ancestors:
        - https://tanzu.academy
        - https://*.tanzu.academy
        - https://*.fixeldev.com
        - https://*.kubeacademy.fixeldev.com
        - http://localhost:8080
  analytics:
    google:
      trackingId: "${ANALYTICS_GOOGLE_ID}"
    clarity:
      trackingId: "${ANALYTICS_CLARITY_ID}"
    amplitude:
      trackingId: "${ANALYTICS_AMPLITUDE_ID}"
  workshops:
  - name: tanzu-gunter-tanzu-tools-configuration
    expires: 30m       # set the default time allocated for the user's session
    orphaned: 10m      # if there is no activity after certain amount of time, delete the session
    deadline: 60m     # the maximum amount of time the learner could extend the session to
    overdue: 2m       # if the sandbox shepherd lock takes longer than this time, let's have the session be deleted
    reserved: ${TRAINING_PORTAL_RESERVED}