name: Deploy Release to Production
run-name: Deploy ${{ github.ref_name }} to Production
concurrency: deploy-production
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-production]
jobs:
  deployment:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make Image for Environment
        run: |
          make deploy-lab version=${{ github.ref_name }} environment=prod
      - name: Deploy to Penguin
        env:
          PENGUINCTL_APIURL: ${{ vars.PENGUINCTL_APIURL }}
          PENGUINCTL_APITOKEN: ${{ secrets.PENGUINCTL_APITOKEN }}
        run: |
          make deploy-lms
